spring:
  application:
    name: futbol
  datasource: 
    url: jdbc:mysql://localhost:3306/wii
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate: #Orm java
      ddl-auto: none
    show-sql: true #Muestra en los logs que consulta se esta ejecutando
    properties:
      hibernate: 
        "[format_sql]": true #Formatea el lenguaje SQL

server: 
  port: 8080
